name: wallpaperpod_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  serverpod_flutter: 1.2.6
  wallpaperpod_client:
    path: ../wallpaperpod_client

  serverpod_auth_shared_flutter: ^1.2.6

  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  image_picker: ^1.0.7
  injectable: ^2.4.1
  get_it: ^7.7.0


dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner:
  flutter_gen_runner:
  injectable_generator:

flutter:
  uses-material-design: true
  generate: true
