name: wallpaperpod_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  wallpaperpod_client:
    path: ../wallpaperpod_client

  intl: ^0.18.1
  serverpod_flutter: 1.2.5
  image_picker: ^1.0.7

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
